http:
  host: "localhost"
  port: "8081"
  
thespacedevs:
  host: "lldev.thespacedevs.com"
  basepath: "2.0.0"
  
nasa:
  protocol: "HTTPS"
  host: "api.nasa.gov"
  api_key: "vej4yJeNbdS1bjusRgsbUGZf0WA9cXOoOV62Kua5"
  events:  
    basepath: "planetary"
    path: "apod"
  patents:
    basepath: "techtransfer"
    path: "patent"
  
validate:
  event_type: "^(Moon Landing|Flyby|Press Event|Docking|Undocking|Landing|Launch|Rehearsal|Relocation|Release|Celestial Event|Unknown|EVA|Berthing|Static Fire|Spacecraft Event|Abort Test|Hatch Opening|Test Flight|Change of Command|Orbital Insertion|Farewell Ceremony|Ambient Pressure Test|Cryoproof Test|Wet Dress Rehearsal)$"
  error_message_type: "Invalid event type, must be one of the next (Moon_Landing|Flyby|Press_Event|Docking|Undocking|Landing) etc!"
  period: "^([0-9]{4}-(0[1-9]|1[0-2])-(0[1-9]|[1-2][0-9]|3[0-1]))|(^[0-9]{4}-(0[1-9]|1[0-2]))|(^[0-9]{4})$"
  error_message_period: "Invalid period, must be (yyyy | yyyy-mm | yyyy-mm-dd)!"
  error_message_notFound: "By your query events not found!"
  tooManyRecords: "We found too many records for your query, try one of the next!"
  
deployed:
  host: "connected-demo-kdo.us-e2.cloudhub.io"
  basepath: "api"
  
slack:
  webhookurl: "https://hooks.slack.com/services/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"
  
ftp:
  host: "ftpupload.net"
  port: "21"
  login: "b7_29890608"
  password: "qwerty"
  workDir: "/htdocs"
  logsDir: "LOGApi/Log.txt"